/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ActionValidator } from "./ActionValidator";
export type { IPrometaAddressRegistry } from "./IPrometaAddressRegistry";
export type { IVaultManager } from "./IVaultManager";
