/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as promDaoGovernanceWrapSol from "./PromDaoGovernanceWrap.sol";
export type { promDaoGovernanceWrapSol };
import type * as promFeesDaoSol from "./PromFeesDao.sol";
export type { promFeesDaoSol };
import type * as helpers from "./helpers";
export type { helpers };
