/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as addressRegistrySol from "./AddressRegistry.sol";
export type { addressRegistrySol };
import type * as actionValidator from "./action-validator";
export type { actionValidator };
import type * as helpers from "./helpers";
export type { helpers };
export type { PromDao } from "./PromDao";
export type { PromDaoGovernanceWrap } from "./PromDaoGovernanceWrap";
