/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AddressRegistry__factory } from "./AddressRegistry__factory";
export { PromDao__factory } from "./PromDao__factory";
