/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAddressRegistry,
  IAddressRegistryInterface,
} from "../../../contracts/PromDaoGovernanceWrap.sol/IAddressRegistry";

const _abi = [
  {
    inputs: [],
    name: "promFeesDao",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAddressRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IAddressRegistryInterface {
    return new utils.Interface(_abi) as IAddressRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAddressRegistry {
    return new Contract(address, _abi, signerOrProvider) as IAddressRegistry;
  }
}
