/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAddressRegistry__factory } from "./IAddressRegistry__factory";
export { IPromFeesDao__factory } from "./IPromFeesDao__factory";
export { PromDaoGovernanceWrap__factory } from "./PromDaoGovernanceWrap__factory";
