/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPrometaAddressRegistry,
  IPrometaAddressRegistryInterface,
} from "../../../../contracts/action-validator/ActionValidator.sol/IPrometaAddressRegistry";

const _abi = [
  {
    inputs: [],
    name: "marketplace",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "vaultManager",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPrometaAddressRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IPrometaAddressRegistryInterface {
    return new utils.Interface(_abi) as IPrometaAddressRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPrometaAddressRegistry {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IPrometaAddressRegistry;
  }
}
