/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAddressRegistry } from "./IAddressRegistry";
export type { ITradeMarketplace } from "./ITradeMarketplace";
export type { PromFieldSettingDao } from "./PromFieldSettingDao";
