/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAddressRegistry__factory } from "./IAddressRegistry__factory";
export { ITradeMarketplace__factory } from "./ITradeMarketplace__factory";
export { PromFieldSettingDao__factory } from "./PromFieldSettingDao__factory";
