/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITradeMarketplace,
  ITradeMarketplaceInterface,
} from "../../../contracts/PromFeesDao.sol/ITradeMarketplace";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    name: "setIsTradeCollectionEnabled",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITradeMarketplace__factory {
  static readonly abi = _abi;
  static createInterface(): ITradeMarketplaceInterface {
    return new utils.Interface(_abi) as ITradeMarketplaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITradeMarketplace {
    return new Contract(address, _abi, signerOrProvider) as ITradeMarketplace;
  }
}
