/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAddressRegistry } from "./IAddressRegistry";
export type { IPromFeesDao } from "./IPromFeesDao";
export type { PromDaoGovernanceWrap } from "./PromDaoGovernanceWrap";
