/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Permit__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "AddressRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AddressRegistry__factory>;
    getContractFactory(
      name: "ReentrancyAttacker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReentrancyAttacker__factory>;
    getContractFactory(
      name: "TERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TERC20__factory>;
    getContractFactory(
      name: "IAddressRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAddressRegistry__factory>;
    getContractFactory(
      name: "IPromFeesDao",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPromFeesDao__factory>;
    getContractFactory(
      name: "PromDaoGovernanceWrap",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PromDaoGovernanceWrap__factory>;
    getContractFactory(
      name: "IAddressRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAddressRegistry__factory>;
    getContractFactory(
      name: "ITradeMarketplace",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITradeMarketplace__factory>;
    getContractFactory(
      name: "PromFieldSettingDao",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PromFieldSettingDao__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Permit",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Permit>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "AddressRegistry",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AddressRegistry>;
    getContractAt(
      name: "ReentrancyAttacker",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ReentrancyAttacker>;
    getContractAt(
      name: "TERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TERC20>;
    getContractAt(
      name: "IAddressRegistry",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IAddressRegistry>;
    getContractAt(
      name: "IPromFeesDao",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IPromFeesDao>;
    getContractAt(
      name: "PromDaoGovernanceWrap",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PromDaoGovernanceWrap>;
    getContractAt(
      name: "IAddressRegistry",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IAddressRegistry>;
    getContractAt(
      name: "ITradeMarketplace",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ITradeMarketplace>;
    getContractAt(
      name: "PromFieldSettingDao",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PromFieldSettingDao>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
